import { Schema, model, InferSchemaType, Types } from "mongoose";

const exerciseSchema = new Schema(
  {
    nombre: { type: String, required: true },
    comentario: { type: String },
    musculosPrincipales: {
      type: [String],
      required: true,
      enum: [
        "Abdominales",
        "Abductores",
        "Aductores",
        "Bíceps",
        "Gemelos",
        "Glúteos",
        "Hombros",
        "Pectorales",
        "Antebrazos",
        "Isquiotibiales",
        "Dorsales",
        "Lumbar",
        "Redondos",
        "Cuello",
        "Cuadríceps",
        "Tríceps",
        "Trapecio",
        "Hombros",
        "Oblicuos",
        "Romboide",
        "Soleo",
      ],
    },
    musculosSecundarios: {
      type: [String],
      enum: [
        "Abdominales",
        "Abductores",
        "Aductores",
        "Bíceps",
        "Gemelos",
        "Glúteos",
        "Hombros",
        "Pectorales",
        "Antebrazos",
        "Isquiotibiales",
        "Dorsales",
        "Lumbar",
        "Redondos",
        "Cuello",
        "Cuadríceps",
        "Tríceps",
        "Trapecio",
        "Hombros",
        "Oblicuos",
        "Romboide",
        "Soleo",
      ],
    },
    materialesNecesarios: {
      type: [String],
      required: true,
      enum: [
        "None",
        "Mancuernas",
        "TRX",
        "Kettlebell",
        "Barra",
        "Machine",
        "Foam Roller",
        "Rack",
        "Banda Elastica",
        "Maza",
        "Balon Medicinal",
        "Banco",
        "Fitball",
        "Saco Búlgaro",
        "Cajón",
        "Landmine",
        "Bosu",
        "Multipower",
        "Polea",
        "Escalera de Coordinación",
        "Valla",
        "Aro",
        "Steps",
        "Disco",
        "Conos",
        "Espaldera",
      ],
    },
    etiquetas: {
      type: [String], 
      required: true,
      enum: [
        "Full Body",
        "Cardio",
        "Tren Superior",
        "Tren Inferior",
        "Core",
        "Movilidad",
        "Estiramiento",
        "Roler",
      ],
    },
    videoUrl: { type: String },
    imageUrl: { type: String },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

type ExerciseType = InferSchemaType<typeof exerciseSchema>;
const Exercise = model<ExerciseType>("Exercise", exerciseSchema);
export default Exercise;
